name: pytest

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  run_pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install the dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest
